fix(edu-sharing-backup): List and unpause all paused Docker containers

diff --git a/ansible/roles/edu-sharing-backup/templates/edu-sharing-backup.sh.j2 b/ansible/roles/edu-sharing-backup/templates/edu-sharing-backup.sh.j2
--- a/ansible/roles/edu-sharing-backup/templates/edu-sharing-backup.sh.j2
+++ b/ansible/roles/edu-sharing-backup/templates/edu-sharing-backup.sh.j2
@@ -35,3 +35,16 @@ if ! eval "${EDU_SHARING_BACKUP_COMMAND}"; then
 else
     echo "Edu-sharing backup initiated successfully."
 fi
+
+# List and unpause all paused Docker containers
+    echo "Unpausing all paused Docker containers..."
+    for container_id in $(docker ps -q -f "status=paused"); do
+        echo "Unpausing Docker container: ${container_id}"
+        docker unpause "${container_id}"
+        if [ $? -ne 0 ]; then
+            echo "Failed to unpause Docker container: ${container_id}"
+        else
+            echo "Docker container unpaused: ${container_id}"
+        fi
+    done
+
